apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.component }}
  annotations:
    eks.amazonaws.com/role-arn:   #arn:aws:iam::655555777:role/prod-eks-ssm-ro role
  labels:
    app.kubernetes.io/name: {{ .Values.component }}