apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.component }}
  annotations:
    eks.amazonaws.com/role-arn:   #arn:aws:iam::655555777:role/prod-eks-ssm-ro role
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
  labels:
    app.kubernetes.io/name: {{ .Values.component }}